import { auditAerisThemeContrast, type AerisThemeContrastReport } from './aeris-contrast';
import {
  AERIS_COLOR_DERIVATION_VERSION,
  type AerisColorDerivationVersion,
} from './aeris-color-derivation';
import { resolveAerisTheme } from './aeris-theme-resolver';
import { resolveAerisThemeTokens, type AerisThemeTokenMap } from './aeris-theme-tokens';
import { type AerisTheme, type AerisThemeOverride } from './aeris-theme';

export interface AerisThemeCssOptions {
  /** Fails generation when the installed color derivation contract differs. */
  readonly expectedDerivationVersion?: number;
  /** Enforces resolved WCAG contrast checks during generation. */
  readonly validateContrast?: boolean;
  /** Single selector that owns the generated variables. */
  readonly selector?: string;
  /** Includes prefers-color-scheme and data-aeris-theme="system" rules. */
  readonly includeSystemMode?: boolean;
  /** Color schemes included in the generated stylesheet. */
  readonly schemes?: AerisThemeSchemes;
  /** Scheme used when the owning element has no data-aeris-theme attribute. */
  readonly defaultMode?: AerisGeneratedThemeMode;
  /** Removes formatting and the generated-file banner. */
  readonly minify?: boolean;
  /** Includes the stable generated-file banner in formatted output. */
  readonly banner?: boolean;
}

export type AerisThemeSchemes = 'both' | 'light' | 'dark';
export type AerisGeneratedThemeMode = 'system' | 'light' | 'dark';

export interface AerisThemeBuildResult {
  readonly derivationVersion: AerisColorDerivationVersion;
  readonly css: string;
  readonly theme: AerisTheme;
  readonly lightTokens: AerisThemeTokenMap;
  readonly darkTokens: AerisThemeTokenMap;
  readonly contrast: Readonly<{
    light: AerisThemeContrastReport;
    dark: AerisThemeContrastReport;
  }>;
}

export interface AerisThemeGenerationIssue {
  readonly code:
    | 'contrast-failed'
    | 'contrast-unresolved'
    | 'invalid-css-value'
    | 'derivation-version-mismatch'
    | 'invalid-density'
    | 'invalid-default-mode'
    | 'invalid-radius'
    | 'invalid-selector';
  readonly message: string;
  readonly mode?: 'light' | 'dark';
  readonly token?: string;
}

export class AerisThemeGenerationError extends Error {
  readonly issues: readonly AerisThemeGenerationIssue[];

  constructor(issues: readonly AerisThemeGenerationIssue[]) {
    super(
      `Aeris theme generation failed with ${issues.length} issue${issues.length === 1 ? '' : 's'}.`,
    );
    this.name = 'AerisThemeGenerationError';
    this.issues = issues;
  }
}

const DEFAULT_SELECTOR = ':root';
const GENERATED_BANNER = `/*! Generated by Aeris UI; color derivation v${AERIS_COLOR_DERIVATION_VERSION}. Edit the theme source, not this file. */`;

/** Resolves, validates, and serializes a complete Aeris theme into deterministic CSS. */
export function compileAerisTheme(
  themeOverride: AerisThemeOverride = {},
  options: AerisThemeCssOptions = {},
): AerisThemeBuildResult {
  const selector = options.selector?.trim() || DEFAULT_SELECTOR;
  const generation = resolveGenerationOptions(options);
  const theme = resolveAerisTheme(themeOverride);
  const lightTokens = resolveAerisThemeTokens(theme, 'light');
  const darkTokens = resolveAerisThemeTokens(theme, 'dark');
  const contrast = {
    light: auditAerisThemeContrast(theme, 'light'),
    dark: auditAerisThemeContrast(theme, 'dark'),
  } as const;
  const issues = [
    ...validateGeneration(selector, theme, lightTokens, darkTokens, contrast, generation),
  ];

  if (
    options.expectedDerivationVersion !== undefined &&
    options.expectedDerivationVersion !== AERIS_COLOR_DERIVATION_VERSION
  ) {
    issues.unshift({
      code: 'derivation-version-mismatch',
      message: `This configuration expects color derivation v${options.expectedDerivationVersion}, but the installed Aeris package provides v${AERIS_COLOR_DERIVATION_VERSION}. Review the theme changes, then update the configured derivation version before regenerating CSS.`,
    });
  }

  if (issues.length) throw new AerisThemeGenerationError(issues);

  return {
    derivationVersion: AERIS_COLOR_DERIVATION_VERSION,
    css: serializeThemeCss(lightTokens, darkTokens, selector, options, generation),
    theme,
    lightTokens,
    darkTokens,
    contrast,
  };
}

/** Convenience API for callers that only need the generated stylesheet. */
export function generateAerisThemeCss(
  themeOverride: AerisThemeOverride = {},
  options: AerisThemeCssOptions = {},
): string {
  return compileAerisTheme(themeOverride, options).css;
}

function validateGeneration(
  selector: string,
  theme: AerisTheme,
  lightTokens: AerisThemeTokenMap,
  darkTokens: AerisThemeTokenMap,
  contrast: Readonly<{ light: AerisThemeContrastReport; dark: AerisThemeContrastReport }>,
  generation: ResolvedGenerationOptions,
): readonly AerisThemeGenerationIssue[] {
  const issues: AerisThemeGenerationIssue[] = [];

  if (!isSafeSelector(selector)) {
    issues.push({
      code: 'invalid-selector',
      message: 'selector must be one non-empty CSS selector without commas, braces, or semicolons.',
    });
  }
  if (!generation.valid) {
    issues.push({
      code: 'invalid-default-mode',
      message: generation.message,
    });
  }
  if (!theme.densities[theme.density]) {
    issues.push({
      code: 'invalid-density',
      message: `The density preset "${theme.density}" is not defined in theme.densities.`,
    });
  }
  if (!theme.radii[theme.radius]) {
    issues.push({
      code: 'invalid-radius',
      message: `The radius preset "${theme.radius}" is not defined in theme.radii.`,
    });
  }

  const modes =
    generation.schemes === 'both'
      ? ([
          ['light', lightTokens],
          ['dark', darkTokens],
        ] as const)
      : ([
          [generation.schemes, generation.schemes === 'light' ? lightTokens : darkTokens],
        ] as const);

  for (const [mode, tokens] of modes) {
    for (const [token, value] of Object.entries(tokens)) {
      if (!isSafeCssValue(value)) {
        issues.push({
          code: 'invalid-css-value',
          message: `${token} contains characters that cannot be emitted safely.`,
          mode,
          token,
        });
      }
    }

    if (generation.validateContrast) {
      for (const check of contrast[mode].checks) {
        if (check.status === 'fail') {
          issues.push({
            code: 'contrast-failed',
            message: `${check.label} is ${check.ratio?.toFixed(2)}:1; ${check.requiredRatio}:1 is required.`,
            mode,
          });
        } else if (check.status === 'unresolved') {
          issues.push({
            code: 'contrast-unresolved',
            message: `${check.label} could not be evaluated from static colors.`,
            mode,
          });
        }
      }
    }
  }

  return issues;
}

function serializeThemeCss(
  lightTokens: AerisThemeTokenMap,
  darkTokens: AerisThemeTokenMap,
  selector: string,
  options: AerisThemeCssOptions,
  generation: ResolvedGenerationOptions,
): string {
  if (generation.schemes !== 'both') {
    const mode = generation.schemes;
    const tokens = Object.entries(mode === 'light' ? lightTokens : darkTokens);
    const rule = formatRule([selector], tokens, mode, options.minify ?? false);
    return finalizeCss([rule], options);
  }

  const includeSystemMode = generation.includeSystemMode;
  const common: [string, string][] = [];
  const light: [string, string][] = [];
  const dark: [string, string][] = [];

  for (const [token, lightValue] of Object.entries(lightTokens)) {
    const darkValue = darkTokens[token as keyof AerisThemeTokenMap];
    if (darkValue === lightValue) common.push([token, lightValue]);
    else light.push([token, lightValue]);
  }
  for (const [token, darkValue] of Object.entries(darkTokens)) {
    if (!(token in lightTokens)) dark.push([token, darkValue]);
    else if (lightTokens[token as keyof AerisThemeTokenMap] !== darkValue) {
      dark.push([token, darkValue]);
    }
  }

  const lightSelectors = [`${selector}[data-aeris-theme='light']`];
  const darkSelectors = [`${selector}[data-aeris-theme='dark']`];
  if (generation.defaultMode === 'light' || generation.defaultMode === 'system') {
    lightSelectors.unshift(selector);
  } else {
    darkSelectors.unshift(selector);
  }
  if (includeSystemMode) lightSelectors.push(`${selector}[data-aeris-theme='system']`);

  const rules = [
    formatRule([selector], common, undefined, options.minify ?? false),
    formatRule(lightSelectors, light, 'light', options.minify ?? false),
    formatRule(darkSelectors, dark, 'dark', options.minify ?? false),
  ];

  if (includeSystemMode) {
    const systemSelectors = [`${selector}[data-aeris-theme='system']`];
    if (generation.defaultMode === 'system') {
      systemSelectors.unshift(`${selector}:not([data-aeris-theme])`);
    }
    const systemRule = formatRule(systemSelectors, dark, 'dark', options.minify ?? false);
    rules.push(formatMediaRule(systemRule, options.minify ?? false));
  }

  return finalizeCss(rules, options);
}

function finalizeCss(rules: readonly string[], options: AerisThemeCssOptions): string {
  const minify = options.minify ?? false;
  const banner = options.banner ?? true;
  const output = rules.filter(Boolean).join(minify ? '' : '\n\n');
  if (minify || !banner) return `${output}${minify ? '' : '\n'}`;
  return `${GENERATED_BANNER}\n${output}\n`;
}

interface ResolvedGenerationOptions {
  readonly schemes: AerisThemeSchemes;
  readonly defaultMode: AerisGeneratedThemeMode;
  readonly includeSystemMode: boolean;
  readonly validateContrast: boolean;
  readonly valid: boolean;
  readonly message: string;
}

function resolveGenerationOptions(options: AerisThemeCssOptions): ResolvedGenerationOptions {
  const schemes = options.schemes ?? 'both';
  const validSchemes = schemes === 'both' || schemes === 'light' || schemes === 'dark';
  const includeSystemMode = schemes === 'both' && (options.includeSystemMode ?? true);
  const validateContrast = options.validateContrast ?? true;
  const defaultMode =
    options.defaultMode ??
    (schemes === 'both' ? (includeSystemMode ? 'system' : 'light') : schemes);
  const validDefaultMode =
    defaultMode === 'system' || defaultMode === 'light' || defaultMode === 'dark';
  const valid =
    validSchemes &&
    validDefaultMode &&
    ((schemes === 'both' && (defaultMode !== 'system' || includeSystemMode)) ||
      schemes === defaultMode);

  return {
    schemes,
    defaultMode,
    includeSystemMode,
    validateContrast,
    valid,
    message: !validSchemes
      ? 'schemes must be "both", "light", or "dark".'
      : !validDefaultMode
        ? 'defaultMode must be "system", "light", or "dark".'
        : schemes === 'both'
          ? 'defaultMode="system" requires system-mode generation to be enabled.'
          : `defaultMode must be "${schemes}" when only the ${schemes} scheme is generated.`,
  };
}

function formatRule(
  selectors: readonly string[],
  tokens: readonly (readonly [string, string])[],
  colorScheme: 'light' | 'dark' | undefined,
  minify: boolean,
): string {
  if (!tokens.length && !colorScheme) return '';

  if (minify) {
    const declarations = [
      ...(colorScheme ? [`color-scheme:${colorScheme}`] : []),
      ...tokens.map(([token, value]) => `${token}:${value}`),
    ];
    return `${selectors.join(',')}{${declarations.join(';')}}`;
  }

  const declarations = [
    ...(colorScheme ? [`  color-scheme: ${colorScheme};`] : []),
    ...tokens.map(([token, value]) => `  ${token}: ${value};`),
  ];
  return `${selectors.join(',\n')} {\n${declarations.join('\n')}\n}`;
}

function formatMediaRule(rule: string, minify: boolean): string {
  if (minify) return `@media(prefers-color-scheme:dark){${rule}}`;
  return `@media (prefers-color-scheme: dark) {\n${rule
    .split('\n')
    .map((line) => `  ${line}`)
    .join('\n')}\n}`;
}

function isSafeSelector(selector: string): boolean {
  return selector.length > 0 && !/[{},;\r\n]/.test(selector);
}

function isSafeCssValue(value: string): boolean {
  return value.length > 0 && !/[;{}\r\n]/.test(value);
}
