import {
  LucideAlertTriangle,
  LucideArchive,
  LucideBarChart3,
  LucideCheck,
  LucideCheckCircle,
  LucideChevronRight,
  LucideClipboard,
  LucideCode,
  LucideCopy,
  LucideDownload,
  LucideEdit,
  LucideExternalLink,
  LucideHeart,
  LucideHome,
  LucideInfo,
  LucideLayers,
  LucideLink,
  LucideMail,
  LucideMenu,
  LucideMinus,
  LucideMonitor,
  LucideMoon,
  LucidePackage,
  LucidePipette,
  LucidePlus,
  LucideRocket,
  LucideSave,
  LucideSearch,
  LucideSun,
  LucideTrash2,
  LucideUpload,
  LucideX,
  LucideZap,
} from '@lucide/angular';

export const DOC_ICONS = {
  AlertTriangle: LucideAlertTriangle,
  Archive: LucideArchive,
  BarChart3: LucideBarChart3,
  Check: LucideCheck,
  CheckCircle: LucideCheckCircle,
  ChevronRight: LucideChevronRight,
  Clipboard: LucideClipboard,
  Code: LucideCode,
  Copy: LucideCopy,
  Download: LucideDownload,
  Edit: LucideEdit,
  ExternalLink: LucideExternalLink,
  Github: LucideCode,
  Info: LucideInfo,
  Layers: LucideLayers,
  Link: LucideLink,
  Mail: LucideMail,
  Menu: LucideMenu,
  Minus: LucideMinus,
  Monitor: LucideMonitor,
  Moon: LucideMoon,
  Package: LucidePackage,
  Pipette: LucidePipette,
  Plus: LucidePlus,
  Rocket: LucideRocket,
  Save: LucideSave,
  Search: LucideSearch,
  Heart: LucideHeart,
  Home: LucideHome,
  Sun: LucideSun,
  Trash2: LucideTrash2,
  Upload: LucideUpload,
  X: LucideX,
  Zap: LucideZap,
} as const;
