import {
  AERIS_COLOR_DERIVATION_VERSION,
  AERIS_THEME_PRESETS,
  AerisThemeGenerationError,
  compileAerisTheme,
  generateAerisThemeCss,
  resolveAerisTheme,
  resolveAerisThemeTokens,
} from '../../../theme-builder/public-api';

describe('Aeris build-time theme generator', () => {
  it('generates deterministic light, dark, and system-mode CSS', () => {
    const first = generateAerisThemeCss(AERIS_THEME_PRESETS.coastal);
    const second = generateAerisThemeCss(AERIS_THEME_PRESETS.coastal);

    expect(first).toBe(second);
    expect(first).toContain(
      `/*! Generated by Aeris UI; color derivation v${AERIS_COLOR_DERIVATION_VERSION}.`,
    );
    expect(first).toContain(":root[data-aeris-theme='light']");
    expect(first).toContain(":root[data-aeris-theme='dark']");
    expect(first).toContain('@media (prefers-color-scheme: dark)');
    expect(first).toContain('--aeris-primary-boundary:');
    expect(first).toContain('--aeris-radius-control:');
  });

  it('reports and enforces the public color derivation contract', () => {
    const result = compileAerisTheme(AERIS_THEME_PRESETS.earth, {
      expectedDerivationVersion: AERIS_COLOR_DERIVATION_VERSION,
    });

    expect(result.derivationVersion).toBe(AERIS_COLOR_DERIVATION_VERSION);
    expectGenerationIssues(
      () =>
        compileAerisTheme(AERIS_THEME_PRESETS.earth, {
          expectedDerivationVersion: AERIS_COLOR_DERIVATION_VERSION + 1,
        }),
      'derivation-version-mismatch',
    );
  });

  it('uses exactly the same resolved token maps as runtime theming', () => {
    const theme = resolveAerisTheme({
      ...AERIS_THEME_PRESETS.orchid,
      density: 'compact',
      radius: 'soft',
    });
    const result = compileAerisTheme(theme);

    expect(result.lightTokens).toEqual(resolveAerisThemeTokens(theme, 'light'));
    expect(result.darkTokens).toEqual(resolveAerisThemeTokens(theme, 'dark'));
    expect(result.contrast.light.status).toBe('pass');
    expect(result.contrast.dark.status).toBe('pass');
  });

  it('emits mode-independent tokens once', () => {
    const css = generateAerisThemeCss(AERIS_THEME_PRESETS.earth);

    expect(css.match(/--aeris-control-height:/g)).toHaveLength(1);
    expect(css.match(/--aeris-radius-md:/g)).toHaveLength(1);
  });

  it('supports compact output, custom ownership, and explicit modes only', () => {
    const css = generateAerisThemeCss(AERIS_THEME_PRESETS.monochrome, {
      selector: '.aeris-preview',
      includeSystemMode: false,
      minify: true,
    });

    expect(css.startsWith('.aeris-preview{')).toBe(true);
    expect(css).toContain(".aeris-preview[data-aeris-theme='dark']");
    expect(css).not.toContain('prefers-color-scheme');
    expect(css).not.toContain('Generated by Aeris UI');
    expect(css).not.toContain('\n');
  });

  it('can emit a single light or dark scheme', () => {
    const light = generateAerisThemeCss(AERIS_THEME_PRESETS.coastal, {
      schemes: 'light',
    });
    const dark = generateAerisThemeCss(AERIS_THEME_PRESETS.coastal, {
      schemes: 'dark',
    });

    expect(light).toContain('color-scheme: light');
    expect(light).not.toContain("data-aeris-theme='dark'");
    expect(light).not.toContain('prefers-color-scheme');
    expect(dark).toContain('color-scheme: dark');
    expect(dark).not.toContain("data-aeris-theme='light'");
    expect(dark).not.toContain('prefers-color-scheme');
  });

  it('supports light or dark defaults while retaining explicit scheme selection', () => {
    const lightDefault = generateAerisThemeCss(AERIS_THEME_PRESETS.earth, {
      defaultMode: 'light',
    });
    const darkDefault = generateAerisThemeCss(AERIS_THEME_PRESETS.earth, {
      defaultMode: 'dark',
    });

    expect(lightDefault).toContain(":root,\n:root[data-aeris-theme='light']");
    expect(darkDefault).toContain(":root,\n:root[data-aeris-theme='dark']");
    expect(lightDefault).toContain('@media (prefers-color-scheme: dark)');
    expect(darkDefault).toContain('@media (prefers-color-scheme: dark)');
  });

  it('rejects incompatible scheme and default-mode combinations', () => {
    expectGenerationIssues(
      () => compileAerisTheme({}, { schemes: 'light', defaultMode: 'dark' }),
      'invalid-default-mode',
    );
    expectGenerationIssues(
      () => compileAerisTheme({}, { defaultMode: 'system', includeSystemMode: false }),
      'invalid-default-mode',
    );
  });

  it('compiles every official preset without accessibility issues', () => {
    for (const preset of Object.values(AERIS_THEME_PRESETS)) {
      const result = compileAerisTheme(preset);

      expect(result.contrast.light.failed).toBe(0);
      expect(result.contrast.light.unresolved).toBe(0);
      expect(result.contrast.dark.failed).toBe(0);
      expect(result.contrast.dark.unresolved).toBe(0);
    }
  });

  it('rejects unsafe selectors and CSS values with actionable issue codes', () => {
    expectGenerationIssues(
      () => compileAerisTheme({}, { selector: ':root, body' }),
      'invalid-selector',
    );
    expectGenerationIssues(
      () =>
        compileAerisTheme({
          palette: { primary: '#123456; color: red' },
        }),
      'invalid-css-value',
    );
  });

  it('allows contrast enforcement to be disabled without disabling CSS safety checks', () => {
    const inaccessibleTheme = {
      light: {
        page: '#ffffff',
        surface: '#ffffff',
        text: '#ffffff',
      },
    } as const;

    expectGenerationIssues(() => compileAerisTheme(inaccessibleTheme), 'contrast-failed');

    const result = compileAerisTheme(inaccessibleTheme, { validateContrast: false });
    expect(result.contrast.light.status).toBe('fail');
    expect(result.css).toContain('--aeris-text: #ffffff');

    expectGenerationIssues(
      () =>
        compileAerisTheme(
          { palette: { primary: '#123456; color: red' } },
          { validateContrast: false },
        ),
      'invalid-css-value',
    );
  });

  it('rejects missing selected density and radius scales', () => {
    expectGenerationIssues(() => compileAerisTheme({ density: 'missing' }), 'invalid-density');
    expectGenerationIssues(() => compileAerisTheme({ radius: 'missing' }), 'invalid-radius');
  });
});

function expectGenerationIssues(
  action: () => unknown,
  expectedCode: AerisThemeGenerationError['issues'][number]['code'],
): void {
  let thrown: unknown;

  try {
    action();
  } catch (error) {
    thrown = error;
  }

  expect(thrown).toBeInstanceOf(AerisThemeGenerationError);
  expect(
    (thrown as AerisThemeGenerationError).issues.some(({ code }) => code === expectedCode),
  ).toBe(true);
}
