import { posix } from 'node:path';
import { lastValueFrom } from 'rxjs';
import {
  SchematicsException,
  Tree,
  callRule,
  type SchematicContext,
} from '@angular-devkit/schematics';
import {
  addRootProvider,
  readWorkspace,
  updateWorkspace,
  type ProjectDefinition,
} from '@schematics/angular/utility';

import { AERIS_COLOR_DERIVATION_VERSION, compileAerisTheme } from '../../theme-builder/public-api';
import { createThemeOverride, type AerisResolvedSetup } from './options';

const BASE_STYLE = 'node_modules/@aeris-ui/core/styles/aeris.css';
const CONTROL_STYLE = 'node_modules/@aeris-ui/core/styles/controls.css';
const MANAGED_TS_MARKER = '// Generated by ng add @aeris-ui/core.';
const MANAGED_CONFIG_MARKER = 'ng add @aeris-ui/core';

export async function getApplicationNames(tree: Tree): Promise<readonly string[]> {
  const workspace = await readWorkspace(tree);
  return [...workspace.projects]
    .filter(([, project]) => project.extensions['projectType'] === 'application')
    .map(([name]) => name);
}

export async function applyAerisSetup(
  tree: Tree,
  context: SchematicContext,
  setup: AerisResolvedSetup,
): Promise<Tree> {
  const workspace = await readWorkspace(tree);
  const project = workspace.projects.get(setup.project);
  if (!project) throw new SchematicsException(`Project "${setup.project}" was not found.`);

  const sourceRoot = normalize(project.sourceRoot ?? posix.join(project.root, 'src'));
  const mainPath = resolveMainPath(project, sourceRoot);
  const providerFiles = findProviderFiles(tree, sourceRoot);
  const generatedCssPath = normalize(posix.join(sourceRoot, 'styles/aeris-theme.css'));
  const themeConfigPath = '/aeris.theme.json';

  if (setup.strategy === 'build-time' && providerFiles.length) {
    throw new SchematicsException(
      `Runtime Aeris configuration already exists in ${providerFiles.join(', ')}. Remove it before switching to build-time theming.`,
    );
  }
  if (
    setup.strategy === 'runtime' &&
    (tree.exists(themeConfigPath) || projectUsesStyle(project, generatedCssPath.slice(1)))
  ) {
    throw new SchematicsException(
      'Build-time Aeris configuration already exists. Remove aeris.theme.json and its generated stylesheet before switching to runtime theming.',
    );
  }

  const files =
    setup.strategy === 'runtime'
      ? prepareRuntimeFiles(tree, setup, sourceRoot, mainPath)
      : prepareBuildTimeFiles(setup, generatedCssPath);
  preflightManagedFiles(tree, files, setup.force);

  for (const [path, content] of files) writeFile(tree, path, content);
  updateDocumentDirection(tree, project, sourceRoot, setup.direction);
  if (setup.strategy === 'build-time') updatePackageScripts(tree);

  const stylePaths = [
    BASE_STYLE,
    CONTROL_STYLE,
    ...(setup.strategy === 'build-time' ? [generatedCssPath.slice(1)] : []),
  ];
  await lastValueFrom(
    callRule(
      updateWorkspace((definition) => {
        const targetProject = definition.projects.get(setup.project);
        const build = targetProject?.targets.get('build');
        if (!build) {
          throw new SchematicsException(
            `Project "${setup.project}" does not have an Angular build target.`,
          );
        }
        const styles = Array.isArray(build.options?.['styles']) ? [...build.options['styles']] : [];
        const withoutAeris = styles.filter(
          (entry) =>
            typeof entry !== 'string' ||
            ![BASE_STYLE, CONTROL_STYLE, generatedCssPath.slice(1)].includes(entry),
        );
        build.options = {
          ...build.options,
          styles: [...withoutAeris, ...stylePaths],
        };
      }),
      tree,
      context,
    ),
  );

  if (setup.strategy === 'runtime' && providerFiles.length === 0) {
    await lastValueFrom(
      callRule(
        addRootProvider(
          setup.project,
          ({ code, external }) =>
            code`${external('provideAeris', '@aeris-ui/core/theming')}(${external('aerisConfig', './aeris.config')})`,
        ),
        tree,
        context,
      ),
    );
  } else if (setup.strategy === 'runtime') {
    const managed = providerFiles.some((path) =>
      tree.readText(path).includes('provideAeris(aerisConfig)'),
    );
    if (!managed) {
      throw new SchematicsException(
        `Aeris is already configured manually in ${providerFiles.join(', ')}. The initializer did not replace that provider.`,
      );
    }
  }

  reportFrameworkDetection(tree, context, project);
  context.logger.info(`Aeris UI configured for Angular project "${setup.project}".`);
  if (setup.strategy === 'build-time') {
    context.logger.info(
      'Generated aeris.theme.json and theme CSS. The start and build scripts now regenerate it.',
    );
  }
  context.logger.info(
    'Aeris works with any icon library. The documentation uses Lucide for consumer-icon examples.',
  );
  return tree;
}

function prepareRuntimeFiles(
  tree: Tree,
  setup: AerisResolvedSetup,
  sourceRoot: string,
  mainPath: string,
): ReadonlyMap<string, string> {
  const configDirectory = findApplicationConfigDirectory(tree, sourceRoot, mainPath);
  const path = normalize(posix.join(configDirectory, 'aeris.config.ts'));
  const presetImport = setup.preset ? 'AERIS_THEME_PRESETS, ' : '';
  const theme = setup.preset
    ? `{
    ...AERIS_THEME_PRESETS.${setup.preset},
    density: '${setup.density}',
    radius: '${setup.corners}',
    direction: '${setup.direction}',
  }`
    : `{
    palette: ${formatObject(setup.seeds ?? {})},
    density: '${setup.density}',
    radius: '${setup.corners}',
    direction: '${setup.direction}',
  }`;
  const mode = setup.schemes === 'both' ? setup.defaultMode : setup.schemes;
  const storage = setup.persistMode ? "'aeris-theme-mode'" : 'false';
  const content = `${MANAGED_TS_MARKER}
import { ${presetImport}type AerisConfig } from '@aeris-ui/core/theming';

export const aerisConfig: AerisConfig = {
  mode: '${mode}',
  themeModeStorageKey: ${storage},
  theme: ${theme},
};
`;
  return new Map([[path, content]]);
}

function prepareBuildTimeFiles(
  setup: AerisResolvedSetup,
  generatedCssPath: string,
): ReadonlyMap<string, string> {
  const theme = {
    ...(setup.seeds ? { palette: setup.seeds } : {}),
    density: setup.density,
    radius: setup.corners,
    direction: setup.direction,
  };
  const config = {
    $schema: './node_modules/@aeris-ui/core/theme-config.schema.json',
    generatedBy: MANAGED_CONFIG_MARKER,
    derivationVersion: AERIS_COLOR_DERIVATION_VERSION,
    preset: setup.preset ?? 'earth',
    output: generatedCssPath.slice(1),
    css: {
      schemes: setup.schemes,
      defaultMode: setup.defaultMode,
      includeSystemMode: setup.schemes === 'both',
    },
    theme,
  };
  const css = compileAerisTheme(createThemeOverride(setup), {
    expectedDerivationVersion: AERIS_COLOR_DERIVATION_VERSION,
    schemes: setup.schemes,
    defaultMode: setup.defaultMode,
    includeSystemMode: setup.schemes === 'both',
  }).css;
  return new Map([
    ['/aeris.theme.json', `${JSON.stringify(config, null, 2)}\n`],
    [generatedCssPath, css],
  ]);
}

function preflightManagedFiles(
  tree: Tree,
  files: ReadonlyMap<string, string>,
  force: boolean,
): void {
  for (const [path, content] of files) {
    if (!tree.exists(path)) continue;
    const existing = tree.readText(path);
    if (existing === content || isManagedFile(path, existing) || force) continue;
    throw new SchematicsException(
      `${path.slice(1)} already exists and is not managed by the Aeris initializer. Re-run with --force to replace it.`,
    );
  }
}

function isManagedFile(path: string, content: string): boolean {
  if (path.endsWith('.ts')) return content.startsWith(MANAGED_TS_MARKER);
  if (path.endsWith('.css')) return content.includes('Generated by Aeris UI');
  if (path.endsWith('.json')) {
    try {
      return JSON.parse(content).generatedBy === MANAGED_CONFIG_MARKER;
    } catch {
      return false;
    }
  }
  return false;
}

function writeFile(tree: Tree, path: string, content: string): void {
  if (tree.exists(path)) tree.overwrite(path, content);
  else tree.create(path, content);
}

function findProviderFiles(tree: Tree, sourceRoot: string): readonly string[] {
  return listFiles(tree).filter(
    (path) =>
      path.startsWith(`${sourceRoot}/`) &&
      path.endsWith('.ts') &&
      tree.readText(path).includes('provideAeris('),
  );
}

function findApplicationConfigDirectory(tree: Tree, sourceRoot: string, mainPath: string): string {
  const candidates = listFiles(tree).filter(
    (path) =>
      path.startsWith(`${sourceRoot}/`) &&
      path.endsWith('.ts') &&
      tree.readText(path).includes('ApplicationConfig'),
  );
  return candidates.length
    ? normalize(posix.dirname(candidates[0]))
    : normalize(posix.dirname(mainPath));
}

function resolveMainPath(project: ProjectDefinition, sourceRoot: string): string {
  const browser = project.targets.get('build')?.options?.['browser'];
  return normalize(typeof browser === 'string' ? browser : posix.join(sourceRoot, 'main.ts'));
}

function updateDocumentDirection(
  tree: Tree,
  project: ProjectDefinition,
  sourceRoot: string,
  direction: 'ltr' | 'rtl',
): void {
  const indexOption = project.targets.get('build')?.options?.['index'];
  const indexPath = normalize(
    typeof indexOption === 'string'
      ? indexOption
      : typeof indexOption === 'object' && indexOption && 'input' in indexOption
        ? String(indexOption['input'])
        : posix.join(sourceRoot, 'index.html'),
  );
  if (!tree.exists(indexPath)) return;
  const source = tree.readText(indexPath);
  const updated = source.replace(/<html\b([^>]*)>/i, (_match, attributes: string) => {
    const next = /\bdir\s*=/.test(attributes)
      ? attributes.replace(/\bdir\s*=\s*(["']).*?\1/i, `dir="${direction}"`)
      : `${attributes} dir="${direction}"`;
    return `<html${next}>`;
  });
  if (updated !== source) tree.overwrite(indexPath, updated);
}

function updatePackageScripts(tree: Tree): void {
  const path = '/package.json';
  if (!tree.exists(path)) return;
  const manifest = JSON.parse(tree.readText(path)) as {
    packageManager?: string;
    scripts?: Record<string, string>;
  };
  const manager = manifest.packageManager?.split('@')[0] ?? 'npm';
  const runTheme =
    manager === 'pnpm'
      ? 'pnpm aeris:theme'
      : manager === 'yarn'
        ? 'yarn aeris:theme'
        : manager === 'bun'
          ? 'bun run aeris:theme'
          : 'npm run aeris:theme';
  const scripts: Record<string, string> = {
    ...manifest.scripts,
    'aeris:theme': 'aeris-theme --config aeris.theme.json',
  };
  scripts['start'] = prefixScript(scripts['start'] ?? 'ng serve', runTheme);
  scripts['build'] = prefixScript(scripts['build'] ?? 'ng build', runTheme);
  manifest.scripts = scripts;
  tree.overwrite(path, `${JSON.stringify(manifest, null, 2)}\n`);
}

function prefixScript(script: string, command: string): string {
  return script.includes('aeris:theme') ? script : `${command} && ${script}`;
}

function reportFrameworkDetection(
  tree: Tree,
  context: SchematicContext,
  project: ProjectDefinition,
): void {
  const packageSource = tree.exists('/package.json') ? tree.readText('/package.json') : '';
  const styles = project.targets.get('build')?.options?.['styles'];
  const styleSource = [
    JSON.stringify(styles ?? []),
    ...(Array.isArray(styles)
      ? styles.flatMap((entry) => {
          const path = typeof entry === 'string' ? normalize(entry) : undefined;
          return path && tree.exists(path) ? [tree.readText(path)] : [];
        })
      : []),
  ].join('\n');
  if (/tailwindcss/i.test(packageSource + styleSource)) {
    context.logger.info('Detected Tailwind CSS. Aeris styles were placed after framework styles.');
  }
  if (/bootstrap/i.test(packageSource + styleSource)) {
    context.logger.info('Detected Bootstrap. Aeris styles were placed after framework styles.');
  }
}

function projectUsesStyle(project: ProjectDefinition, style: string): boolean {
  const styles = project.targets.get('build')?.options?.['styles'];
  return Array.isArray(styles) && styles.some((entry) => entry === style);
}

function formatObject(value: object): string {
  return JSON.stringify(value, null, 2)
    .split('\n')
    .map((line, index) => (index === 0 ? line : `    ${line}`))
    .join('\n');
}

function normalize(path: string): string {
  return `/${path.replaceAll('\\', '/').replace(/^\/+/, '')}`;
}

function listFiles(tree: Tree): readonly string[] {
  const files: string[] = [];
  tree.root.visit((path) => files.push(normalize(String(path))));
  return files;
}
